<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AltensorAccounting.Domain\AltensorAccounting.Domain.csproj" />
    <ProjectReference Include="..\AltensorAccounting.Contract\AltensorAccounting.Contract.csproj" />
  </ItemGroup>

</Project>
